### ISSUE TITLE
ACCESS MED setup failing

### ISSUE THREAD

**Issue by rbeucher** [coecms/cms-conda-singularity#20]
Hi @dsroberts,

I am trying to set up a conda environment for MED using your singularity setup.

see here:

https://github.com/ACCESS-NRI/MED-condaenv/pulls

The initialisation is failing when calling singularity:

```/opt/singularity/bin/singularity -s exec --bind /etc,/half-root,/local,/ram,/run,/system,/usr,/var/lib/sss,/var/run/munge,/var/lib/rpm,/jobfs/84698570.gadi-pbs/overlay/:/g /g/data/xp65/admin/MED-condaenv/container/base.sif /g/data/xp65/admin/MED-condaenv/scripts/initialise.sh --inner```

for some reason, singularity cannot see the `initialise.sh` script.

```
FATAL:   stat /g/data/xp65/admin/MED-condaenv/scripts/initialise.sh: no such file or directory
```

Any idea?

Romain

**Comment by dsroberts** [comment]
This issue is actually intended behaviour. This part of the `--bind` flags: `/jobfs/84698570.gadi-pbs/overlay/:/g` replaces the default bind mount at `/g` (which is just Gadi's `/g`), with an empty directory in `$PBS_JOBFS`. This guarantees that the in-progress installation or update is completely isolated from the existing installation, and can therefore be deployed (or, crucially, not deployed in case of failure) without any effect on the existing installation. Solution is to run `install.sh` from a filesystem that is not `/g/data`. I run it out of `/home`, as the repository is pretty small.

**Comment by rbeucher** [comment]
Thanks @dsroberts. That makes sense.
I move the repo to my home.
I got the build to work.
Now the testing fails for probably the same reason.

```
diff: /g/data/xp65/admin/conda_concept/admin/staging/deployed.yml: No such file or directory
diff: /g/data/xp65/admin/conda_concept/admin/staging/deployed.old.yml: No such file or directory
tar: /g/data/xp65/admin/conda_concept/admin/staging/conda_base.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
FATAL:   while loading overlay images: failed to open overlay image /g/data/xp65/admin/conda_concept/admin/staging/med-conda-0.1.sqsh.tmp: failed to retrieve path for /g/data/xp65/admin/conda_concept/admin/staging/med-conda-0.1.sqsh.tmp: lstat /g/data/xp65/admin/conda_concept/admin/staging/med-conda-0.1.sqsh.tmp: no such file or directory
```

The thing is you also define your admin folder to be on `gdata`.

What am I missing?

**Comment by dsroberts** [comment]
@rbeucher that part of the test script is run outside of the container, so those paths should exist at that point. You may want to double-check that those files are where you expect. The build scripts ends with `|| true` to handle missing `deployed.old.yml` files in the case of a brand new installation. If the actual container build passed, but the copying at the end fails, the build will still report passed because of that.

**Comment by rbeucher** [comment]
Thanks @dsroberts.

I got it to work.

Question: This is the structure I get in the module after deployment:

```
modules
`-- conda
    |-- .access-med-0.1
    |-- .modulerc
    |-- access-med-0.1 -> .common_v3
    `-- conda
        `-- .common_v3
```

It expects `.common_v3` to be in the first level `conda` folder. Although, there is another sub-folder called `conda/conda`
Is it intended behaviour?

Here is a link to my config:
https://github.com/ACCESS-NRI/MED-condaenv/blob/main/scripts/install_config.sh

R

**Comment by dsroberts** [comment]
Nope, not intended. I see what I did there. This line: https://github.com/coecms/cms-conda-singularity/blob/3a2540ceffb4b946f8c1326ffa019c6e6511762c/scripts/initialise.sh#LL30C22-L30C22
has an extra `${MODULE_NAME}`, this is already included in `${CONDA_MODULE_PATH}`

**Comment by rbeucher** [comment]
You want me to submit a PR for a fix?

**Comment by dsroberts** [comment]
I'm just about to do it along with another error I found

**Comment by rbeucher** [comment]
Also, I have added some conditions here.

https://github.com/coecms/cms-conda-singularity/compare/main...ACCESS-NRI:MED-condaenv:main#diff-3d64996115d0ac3b74e36f57ce6b00d6b4982614c41b1ed39eab8ef43b2e9a2b

It was breaking for the minimal example I was trying to set up.

**Comment by rbeucher** [comment]
Thanks. I got it to work on the CLI. Now I am trying with ARE. 
I had commented out `jupyter build`. I turned it back on and it is failing... of course :-/

Hre is the extract of the job error output:

```
Please update conda by running

    $ conda update -n base -c defaults conda


[LabBuildApp] JupyterLab 4.0.0
[LabBuildApp] Building in /jobfs/85145911.gadi-pbs/squashfs-root/opt/conda/access-med-0.1/share/jupyter/lab
[LabBuildApp] ERROR | Build failed.
Troubleshooting: If the build failed due to an out-of-memory error, you
may be able to fix it by disabling the `dev_build` and/or `minimize` options.

If you are building via the `jupyter lab build` command, you can disable
these options like so:

jupyter lab build --dev-build=False --minimize=False

You can also disable these options for all JupyterLab builds by adding these
lines to a Jupyter config file named `jupyter_config.py`:

c.LabBuildApp.minimize = False
c.LabBuildApp.dev_build = False

If you don't already have a `jupyter_config.py` file, you can create one by
adding a blank file of that name to any of the Jupyter config directories.
The config directories can be listed by running:

jupyter --paths

Explanation:

- `dev-build`: This option controls whether a `dev` or a more streamlined
`production` build is used. This option will default to `False` (i.e., the
`production` build) for most users. However, if you have any labextensions
installed from local files, this option will instead default to `True`.
Explicitly setting `dev-build` to `False` will ensure that the `production`
build is used in all circumstances.

- `minimize`: This option controls whether your JS bundle is minified
during the Webpack build, which helps to improve JupyterLab's overall
performance. However, the minifier plugin used by Webpack is very memory
intensive, so turning it off may help the build finish successfully in
low-memory environments.

/g/data/xp65/public/apps/med_conda/envs/access-med-0.1/lib/python3.10/site-packages/jupyterlab/debuglog.py:56: UserWarning: An error occurred.
  warnings.warn("An error occurred.")
/g/data/xp65/public/apps/med_conda/envs/access-med-0.1/lib/python3.10/site-packages/jupyterlab/debuglog.py:57: UserWarning: ValueError: Please install Node.js and npm before continuing installation. You may be able to install Node.js from your package manager, from conda, or directly from the Node.js website (https://nodejs.org).
  warnings.warn(msg[-1].strip())
/g/data/xp65/public/apps/med_conda/envs/access-med-0.1/lib/python3.10/site-packages/jupyterlab/debuglog.py:58: UserWarning: See the log file for details: /jobfs/85145911.gadi-pbs/jupyterlab-debug-7ju_dqfv.log
  warnings.warn(f"See the log file for details: {log_path!s}")
```

**Comment by dsroberts** [comment]
My understanding of `jupyter build` is that it relates specifically to optional notebook assets like `dask-labextension`. So with your minimal environment, it probably isn't necessary. You know you'll need it when you start getting popups like:
```
JupyterLab build is suggested:

dask-labextension needs to be included in build
```
on connecting to a jupyterlab session. And the error tells you how to fix it anyway.
```
Please install Node.js and npm before continuing installation. You may be able to install Node.js from your package manager, from conda...
```
For what its worth, `npm` doesn't appear necessary. The `jupyter build` command completes in the `hh5` envs just fine without it.
