### ISSUE TITLE
Bug trying to deploy the ACCESS-MED environment after major update

### ISSUE THREAD

**Issue by rbeucher** [coecms/cms-conda-singularity#65]
Hi @dsroberts 

https://github.com/coecms/cms-conda-singularity/blob/95153675ad7031e68ad9a1b254b7e437bb6e8a8d/scripts/build.sh#L30C2-L30C45

The line above fails for me. 

I am not sure I understand what this does.
I have a `~/.conda` folder but no `~/.mamba` or `~/micromamba`

R

**Comment by dsroberts** [comment]
Hi @rbeucher 

This bit of code deals with the directories used by conda and/or micromamba in a users home directory. Our analysis environments are pretty large, so its entirely possible for a conda update to fill a user's home quota. Moreover, the small file operations performed during conda installations are extremely slow on NFS file systems. For this reason, we do as much as we can on `$PBS_JOBFS`. I had that bit of code set up assuming those paths were already symlinks, which they aren't in your case. Part of the update in #66 is new code to handle the case where any of those paths is a directory, or when they don't exist.

Dale

**Comment by rbeucher** [comment]
Great, thanks for the update @dsroberts !
