### ISSUE TITLE
Missing hwloc library?

### ISSUE THREAD

**Issue by rbeucher** [coecms/cms-conda-singularity#67]
Hi @dsroberts

My environment builds but when testing, I get the following error:

`cdo: symbol lookup error: /opt/conda/access-med-0.6/bin/../lib/./libmpi.so.40: undefined symbol: opal_hwloc201_hwloc_bitmap_isincluded`

R

**Comment by rbeucher** [comment]
@dsroberts have you had that issue? Should that one be mounted from the host system or should it be installed in the conda environment?

**Comment by dsroberts** [comment]
I suspect this is an issue with the version of openmpi being bought in by conda. Your scripts are still configured to replace openmpi with openmpi/4.1.5 from /apps, but conda is probably bringing in a newer version. The code that does this replacement goes through the files in {{/apps/openmpi/4.1.5}} and replaces the corresponding files in the conda environment with symlinks to /apps. If openmpi/4.1.6 is in the conda environment, there will be inconsistencies between shared object names or include files or something, so you'll get this partial replacement which probably won't work. You'll need to pin the openmpi conda package to whatever the latest version in /apps is, in this case, 4.1.5. When NCI updates OpenMPI, you can remove the pin, and also update this line: https://github.com/ACCESS-NRI/MED-condaenv/blob/f1a3779f01c55c6b2572c0d77a4d5f80a3a5393b/environments/access-med/config.sh#L21 accordingly.

**Comment by rbeucher** [comment]
OK great thanks for helping with that. I'll try that. That makes sense.

**Comment by rbeucher** [comment]
All good closing this one
