### ISSUE TITLE
Link to COECMS wiki doc for the containerised environment

### ISSUE THREAD

**Issue by rbeucher** [coecms/cms-conda-singularity#86]
Hi @dsroberts and @paolap,

I noticed this morning that the link to the Conda setup guide (https://climate-cms.org/cms-wiki/resources/resources-conda-setup.html) is no longer working.

Before COECMS shuts down, I’d like to ensure that the relevant information is copied to the MED-Condaenv. Could you please point me to where I can find the documentation or an alternative source for this information?

Thanks in advance for your help!

Best regards,
Romain

**Comment by paolap** [comment]
You can find the repository for that jupyter book in our github organisation. If you can find it let me know

**Comment by rbeucher** [comment]
OK found it
https://github.com/coecms/cms-wiki/blob/main/Wiki/resources/resources-conda-setup.md
